joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

shoulder_pan_joint_position:
  type: position_controllers/JointPositionController
  joint: shoulder_pan_joint
  p: 100
  d: 1
  i: 50
  i_clamp: 1
shoulder_lift_joint_position:
  type: position_controllers/JointPositionController
  joint: shoulder_lift_joint
  p: 100
  d: 1
  i: 50
  i_clamp: 1
elbow_joint_position:
  type: position_controllers/JointPositionController
  joint: elbow_joint
  p: 100
  d: 1
  i: 50
  i_clamp: 1
wrist_1_joint_position:
  type: position_controllers/JointPositionController
  joint: wrist_1_joint
  p: 100
  d: 1
  i: 50
  i_clamp: 1
wrist_2_joint_position:
  type: position_controllers/JointPositionController
  joint: wrist_2_joint
  p: 100
  d: 1
  i: 50
  i_clamp: 1
wrist_3_joint_position:
  type: position_controllers/JointPositionController
  joint: wrist_3_joint
  p: 100
  d: 1
  i: 50
  i_clamp: 1
