conveyor:

  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  effort_controller:
    type: effort_controllers/JointPositionController
    joint: conveyor_joint
    p: 100
    d: 1
    i: 50
